# Generated by Django 4.2.29 on 2026-03-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сервиса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Валюта')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно'), ('weekly', 'Еженедельно')], default='monthly', max_length=20, verbose_name='Период оплаты')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('next_payment_date', models.DateField(verbose_name='Дата следующего платежа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['next_payment_date'],
            },
        ),
    ]
